import { sha256Hex } from "../auth/crypto";
import {
  ATTACHMENT_MAX_BYTES,
  ATTACHMENT_ORPHAN_TTL_MS,
  AttachmentError,
  type AttachmentFileRecord,
  type AttachmentObjectStore,
  type AttachmentPayload,
  type AttachmentRepository,
  type AttachmentSetCreateResult,
  type AttachmentSetRecord,
  type AttachmentUploadInput,
  type StoredAttachmentFile,
} from "./contracts";
import { assertAttachmentSetCapacity, validateAttachmentInput } from "./policy";

export interface AttachmentServiceOptions {
  now?: () => string;
  id?: (prefix: string) => string;
  objectKey?: (attachmentSetId: string, fileId: string) => string;
}

export interface AttachmentCleanupResult {
  setId: string;
  deletedFileIds: readonly string[];
  failedFileIds: readonly string[];
  setDeleted: boolean;
}

export interface AttachmentOrphanCleanupResult {
  sets: readonly AttachmentCleanupResult[];
  attempted: number;
  deleted: number;
}

function defaultId(prefix: string): string {
  return `${prefix}_${crypto.randomUUID()}`;
}

function defaultObjectKey(attachmentSetId: string, fileId: string): string {
  // IDs are generated by this service and object keys never include user
  // supplied filenames, mailbox addresses, or message content.
  return `attachment-sets/${attachmentSetId}/${fileId}`;
}

function nowIso(now: () => string): string {
  const value = now();
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) throw new AttachmentError("invalid_input", "The attachment timestamp is invalid");
  return new Date(parsed).toISOString();
}

function orphanExpiry(createdAt: string): string {
  return new Date(Date.parse(createdAt) + ATTACHMENT_ORPHAN_TTL_MS).toISOString();
}

function bytesToArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  return bytes.slice().buffer;
}

/** Coordinates policy validation, D1 metadata, and private object bytes. */
export class AttachmentService {
  private readonly now: () => string;
  private readonly id: (prefix: string) => string;
  private readonly objectKey: (attachmentSetId: string, fileId: string) => string;

  constructor(
    private readonly repository: AttachmentRepository,
    private readonly objectStore: AttachmentObjectStore,
    options: AttachmentServiceOptions = {},
  ) {
    this.now = options.now ?? (() => new Date().toISOString());
    this.id = options.id ?? defaultId;
    this.objectKey = options.objectKey ?? defaultObjectKey;
  }

  async createSet(ownerUserId: string, uploadIdempotencyKey: string): Promise<AttachmentSetCreateResult> {
    const key = uploadIdempotencyKey.trim();
    if (!ownerUserId.trim() || !key || key.length > 200 || /[\u0000-\u001f\u007f]/u.test(key)) {
      throw new AttachmentError("invalid_input", "A valid attachment upload idempotency key is required");
    }
    const existing = await this.repository.getSetByUploadIdempotencyKey(ownerUserId, key);
    if (existing) return { set: existing, created: false };

    const createdAt = nowIso(this.now);
    const set: AttachmentSetRecord = {
      id: this.id("attachment_set"),
      ownerUserId,
      campaignId: null,
      uploadIdempotencyKey: key,
      fileCount: 0,
      totalBytes: 0,
      state: "open",
      expiresAt: orphanExpiry(createdAt),
      lockedAt: null,
      deletedAt: null,
      createdAt,
      updatedAt: createdAt,
    };
    try {
      await this.repository.createSet(set);
      return { set, created: true };
    } catch (error) {
      // A concurrent first request can win the unique owner/key insert. Make
      // that race idempotent by returning the durable winner.
      const winner = await this.repository.getSetByUploadIdempotencyKey(ownerUserId, key);
      if (winner) return { set: winner, created: false };
      throw error;
    }
  }

  async addFile(ownerUserId: string, attachmentSetId: string, input: AttachmentUploadInput): Promise<StoredAttachmentFile> {
    const set = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!set) throw new AttachmentError("not_found", "Attachment set not found");
    if (set.state !== "open" || set.campaignId) {
      throw new AttachmentError("immutable", "This attachment set can no longer be changed");
    }

    const validated = validateAttachmentInput(input);
    const digest = await sha256Hex(validated.bytes);
    const files = await this.repository.listFiles(set.id);
    if (files.some((file) => file.deletedAt === null && file.sha256 === digest)) {
      throw new AttachmentError("duplicate_file", "That attachment has already been selected");
    }
    assertAttachmentSetCapacity(set.fileCount, set.totalBytes, validated.bytes.byteLength);

    const createdAt = nowIso(this.now);
    const fileId = this.id("attachment_file");
    const file: AttachmentFileRecord = {
      id: fileId,
      attachmentSetId: set.id,
      objectKey: this.objectKey(set.id, fileId),
      originalFilename: validated.filename,
      mediaType: validated.mediaType,
      byteSize: validated.bytes.byteLength,
      sha256: digest,
      position: set.fileCount + 1,
      createdAt,
      deletedAt: null,
    };

    let objectStored = false;
    let objectCleanupAttempted = false;
    try {
      await this.objectStore.put(file.objectKey, bytesToArrayBuffer(validated.bytes), {
        httpMetadata: { contentType: file.mediaType },
        customMetadata: { sha256: file.sha256 },
      });
      objectStored = true;
      const inserted = await this.repository.createFile(file, ownerUserId);
      if (!inserted) {
        await this.deleteObjectAfterFailedInsert(file.objectKey);
        objectCleanupAttempted = true;
        const latest = await this.repository.getSetByIdForOwner(set.id, ownerUserId);
        if (!latest || latest.state !== "open" || latest.campaignId) {
          throw new AttachmentError("immutable", "This attachment set can no longer be changed");
        }
        if (latest.fileCount >= 5) throw new AttachmentError("file_limit_exceeded", "A campaign can contain at most 5 attachments");
        if (latest.totalBytes + file.byteSize > ATTACHMENT_MAX_BYTES) {
          throw new AttachmentError("size_limit_exceeded", "The combined attachment size exceeds 2 MiB");
        }
        const latestFiles = await this.repository.listFiles(set.id);
        if (latestFiles.some((entry) => entry.sha256 === digest)) {
          throw new AttachmentError("duplicate_file", "That attachment has already been selected");
        }
        throw new AttachmentError("storage_error", "The attachment could not be recorded");
      }
      const current = await this.repository.getSetByIdForOwner(set.id, ownerUserId);
      return { set: current ?? { ...set, fileCount: set.fileCount + 1, totalBytes: set.totalBytes + file.byteSize, updatedAt: createdAt }, file };
    } catch (error) {
      // If the database write failed after the object was put, remove the
      // private object best-effort. The metadata path remains retryable.
      if (objectStored && !objectCleanupAttempted) await this.deleteObjectAfterFailedInsert(file.objectKey);
      throw error;
    }
  }

  async removeFile(ownerUserId: string, attachmentSetId: string, fileId: string): Promise<boolean> {
    const set = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!set) throw new AttachmentError("not_found", "Attachment set not found");
    if (set.state !== "open" || set.campaignId) {
      throw new AttachmentError("immutable", "This attachment set can no longer be changed");
    }
    const file = await this.repository.getFileByIdForOwner(fileId, attachmentSetId, ownerUserId);
    if (!file) return false;
    // Delete bytes first. If the object store is temporarily unavailable, the
    // row remains so the client can retry without losing the metadata needed
    // for cleanup.
    await this.objectStore.delete(file.objectKey);
    return this.repository.removeFile(file.id, attachmentSetId, ownerUserId, file.byteSize, nowIso(this.now));
  }

  async lockForSnapshot(ownerUserId: string, attachmentSetId: string): Promise<AttachmentSetRecord> {
    const existing = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!existing) throw new AttachmentError("not_found", "Attachment set not found");
    if (existing.state === "deleted") throw new AttachmentError("immutable", "This attachment set has been deleted");
    if (existing.state === "locked") return existing;
    const now = nowIso(this.now);
    const changed = await this.repository.lockSet(attachmentSetId, ownerUserId, now);
    if (!changed) {
      const latest = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
      if (latest?.state === "locked") return latest;
      throw new AttachmentError("immutable", "This attachment set can no longer be changed");
    }
    const locked = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!locked) throw new AttachmentError("not_found", "Attachment set not found");
    return locked;
  }

  async associateWithCampaign(ownerUserId: string, attachmentSetId: string, campaignId: string): Promise<AttachmentSetRecord> {
    const existing = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!existing) throw new AttachmentError("not_found", "Attachment set not found");
    if (existing.state === "deleted") throw new AttachmentError("immutable", "This attachment set has been deleted");
    if (existing.campaignId === campaignId) return existing;
    if (existing.campaignId && existing.campaignId !== campaignId) {
      throw new AttachmentError("already_associated", "This attachment set belongs to another campaign");
    }
    const changed = await this.repository.associateSet(attachmentSetId, ownerUserId, campaignId, nowIso(this.now));
    if (!changed) {
      const latest = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
      if (latest?.campaignId === campaignId) return latest;
      if (latest?.campaignId) throw new AttachmentError("already_associated", "This attachment set belongs to another campaign");
      throw new AttachmentError("immutable", "This attachment set can no longer be changed");
    }
    const associated = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!associated) throw new AttachmentError("not_found", "Attachment set not found");
    return associated;
  }

  async readFile(file: AttachmentFileRecord): Promise<AttachmentPayload> {
    if (file.deletedAt) throw new AttachmentError("storage_error", "This attachment is no longer available");
    const object = await this.objectStore.get(file.objectKey);
    if (!object) throw new AttachmentError("storage_error", "The attachment object is missing");
    let bytes: Uint8Array;
    try {
      bytes = new Uint8Array(await object.arrayBuffer());
    } catch {
      throw new AttachmentError("storage_error", "The attachment object could not be read");
    }
    if (bytes.byteLength !== file.byteSize) {
      throw new AttachmentError("integrity_error", "The attachment size does not match its metadata");
    }
    if ((await sha256Hex(bytes)) !== file.sha256) {
      throw new AttachmentError("integrity_error", "The attachment checksum does not match its metadata");
    }
    return { file, bytes };
  }

  async readSet(ownerUserId: string, attachmentSetId: string): Promise<AttachmentPayload[]> {
    const set = await this.repository.getSetByIdForOwner(attachmentSetId, ownerUserId);
    if (!set) throw new AttachmentError("not_found", "Attachment set not found");
    if (set.state === "deleted") throw new AttachmentError("storage_error", "This attachment set is no longer available");
    const files = await this.repository.listFiles(attachmentSetId);
    const payloads: AttachmentPayload[] = [];
    for (const file of files) payloads.push(await this.readFile(file));
    return payloads;
  }

  async cleanupSetBytes(attachmentSetId: string): Promise<AttachmentCleanupResult> {
    const set = await this.repository.getSetById(attachmentSetId);
    if (!set) return { setId: attachmentSetId, deletedFileIds: [], failedFileIds: [], setDeleted: true };
    const timestamp = nowIso(this.now);
    const deletedFileIds: string[] = [];
    const failedFileIds: string[] = [];
    const files = await this.repository.listFiles(attachmentSetId);
    for (const file of files) {
      try {
        await this.objectStore.delete(file.objectKey);
        await this.repository.markFileBytesDeleted(file.id, timestamp);
        deletedFileIds.push(file.id);
      } catch {
        // Leave metadata untouched so a later scheduled run can retry. R2
        // delete is idempotent, so a successful delete followed by a D1
        // transient error is safe to repeat.
        failedFileIds.push(file.id);
      }
    }
    if (failedFileIds.length > 0) {
      return { setId: attachmentSetId, deletedFileIds, failedFileIds, setDeleted: set.state === "deleted" };
    }
    const remaining = await this.repository.listFiles(attachmentSetId);
    let setDeleted = set.state === "deleted";
    if (remaining.length === 0 && set.state !== "deleted") {
      setDeleted = await this.repository.markSetBytesDeleted(attachmentSetId, timestamp);
    }
    return { setId: attachmentSetId, deletedFileIds, failedFileIds, setDeleted };
  }

  async cleanupExpiredOrphans(limit = 100): Promise<AttachmentOrphanCleanupResult> {
    const sets = await this.repository.listOrphanSets(nowIso(this.now), Math.max(1, Math.min(500, Math.floor(limit))));
    const results: AttachmentCleanupResult[] = [];
    for (const set of sets) results.push(await this.cleanupSetBytes(set.id));
    return {
      sets: results,
      attempted: results.length,
      deleted: results.filter((result) => result.setDeleted).length,
    };
  }

  private async deleteObjectAfterFailedInsert(objectKey: string): Promise<void> {
    try {
      await this.objectStore.delete(objectKey);
    } catch {
      // The metadata insert did not complete, so this orphan is not reachable
      // by a set cleanup query. The object-key namespace is private and the
      // scheduled object-store sweep can remove stale keys operationally.
    }
  }
}

export function createAttachmentService(
  repository: AttachmentRepository,
  objectStore: AttachmentObjectStore,
  options: AttachmentServiceOptions = {},
): AttachmentService {
  return new AttachmentService(repository, objectStore, options);
}
